const data = {
  'nodes': [{
    'id': 'Myriel',
  }, {
    'id': 'Napoleon',
  }, {
    'id': 'Mlle.Baptistine',
  }, {
    'id': 'Mme.Magloire',
  }, {
    'id': 'CountessdeLo',
  }, {
    'id': 'Geborand',
  }, {
    'id': 'Champtercier',
  }, {
    'id': 'Cravatte',
  }, {
    'id': 'Count',
  }, {
    'id': 'OldMan',
  }, {
    'id': 'Labarre',
  }, {
    'id': 'Valjean',
  }, {
    'id': 'Marguerite',
  }, {
    'id': 'Mme.deR',
  }, {
    'id': 'Isabeau',
  }, {
    'id': 'Gervais',
  }, {
    'id': 'Tholomyes',
  }, {
    'id': 'Listolier',
  }, {
    'id': 'Fameuil',
  }, {
    'id': 'Blacheville',
  }, {
    'id': 'Favourite',
  }, {
    'id': 'Dahlia',
  }, {
    'id': 'Zephine',
  }, {
    'id': 'Fantine',
  }],
  'edges': [{
    'source': 'Napoleon',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Mlle.Baptistine',
    'target': 'Myriel',
    'value':  8,
  }, {
    'source': 'Mme.Magloire',
    'target': 'Myriel',
    'value':  10,
  }, {
    'source': 'Mme.Magloire',
    'target': 'Mlle.Baptistine',
    'value':  6,
  }, {
    'source': 'CountessdeLo',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Geborand',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Champtercier',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Cravatte',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Count',
    'target': 'Myriel',
    'value':  2,
  }, {
    'source': 'OldMan',
    'target': 'Myriel',
    'value':  1,
  }, {
    'source': 'Valjean',
    'target': 'Labarre',
    'value':  1,
  }, {
    'source': 'Valjean',
    'target': 'Mme.Magloire',
    'value':  3,
  }, {
    'source': 'Valjean',
    'target': 'Mlle.Baptistine',
    'value':  3,
  }, {
    'source': 'Valjean',
    'target': 'Myriel',
    'value':  5,
  }, {
    'source': 'Marguerite',
    'target': 'Valjean',
    'value':  1,
  }, {
    'source': 'Mme.deR',
    'target': 'Valjean',
    'value':  1,
  }, {
    'source': 'Isabeau',
    'target': 'Valjean',
    'value':  1,
  }, {
    'source': 'Gervais',
    'target': 'Valjean',
    'value':  1,
  }, {
    'source': 'Listolier',
    'target': 'Tholomyes',
    'value':  4,
  }, {
    'source': 'Fameuil',
    'target': 'Tholomyes',
    'value':  4,
  }, {
    'source': 'Fameuil',
    'target': 'Listolier',
    'value':  4,
  }, {
    'source': 'Blacheville',
    'target': 'Tholomyes',
    'value':  4,
  }, {
    'source': 'Blacheville',
    'target': 'Listolier',
    'value':  4,
  }, {
    'source': 'Blacheville',
    'target': 'Fameuil',
    'value':  4,
  }, {
    'source': 'Favourite',
    'target': 'Tholomyes',
    'value':  3,
  }, {
    'source': 'Favourite',
    'target': 'Listolier',
    'value':  3,
  }, {
    'source': 'Favourite',
    'target': 'Fameuil',
    'value':  3,
  }, {
    'source': 'Favourite',
    'target': 'Blacheville',
    'value':  4,
  }, {
    'source': 'Dahlia',
    'target': 'Tholomyes',
    'value':  3,
  }, {
    'source': 'Dahlia',
    'target': 'Listolier',
    'value':  3,
  }, {
    'source': 'Dahlia',
    'target': 'Fameuil',
    'value':  3,
  }, {
    'source': 'Dahlia',
    'target': 'Blacheville',
    'value':  3,
  }, {
    'source': 'Dahlia',
    'target': 'Favourite',
    'value':  5,
  }, {
    'source': 'Zephine',
    'target': 'Tholomyes',
    'value':  3,
  }, {
    'source': 'Zephine',
    'target': 'Listolier',
    'value':  3,
  }, {
    'source': 'Zephine',
    'target': 'Fameuil',
    'value':  3,
  }, {
    'source': 'Zephine',
    'target': 'Blacheville',
    'value':  3,
  }, {
    'source': 'Zephine',
    'target': 'Favourite',
    'value':  4,
  }, {
    'source': 'Zephine',
    'target': 'Dahlia',
    'value':  4,
  }, {
    'source': 'Fantine',
    'target': 'Tholomyes',
    'value':  3,
  }, {
    'source': 'Fantine',
    'target': 'Listolier',
    'value':  3,
  }, {
    'source': 'Fantine',
    'target': 'Fameuil',
    'value':  3,
  }, {
    'source': 'Fantine',
    'target': 'Blacheville',
    'value':  3,
  }, {
    'source': 'Fantine',
    'target': 'Favourite',
    'value':  4,
  }, {
    'source': 'Fantine',
    'target': 'Dahlia',
    'value':  4,
  }, {
    'source': 'Fantine',
    'target': 'Zephine',
    'value':  4,
  }, {
    'source': 'Fantine',
    'target': 'Marguerite',
    'value':  2,
  }, {
    'source': 'Fantine',
    'target': 'Valjean',
    'value':  9,
  }],
};

export default data;
